name: ci

on:
  workflow_dispatch:
  push:
    paths:
        - Dockerfile 
        - .github/workflows/** 
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    uses: thewillyP/ReusableWorkflow/.github/workflows/main.yml@main
    with:
      image_name: vanilla-rtrl
      tag: 1.0.${{ github.run_number }}
    secrets: inherit
